services:
  postgres_db:
    environment:
      - POSTGRES_DB=amelia
      - POSTGRES_USER=amelia
      - POSTGRES_PASSWORD=amelia
    image: postgres:15.4-alpine
    ports: # Set up ports exposed for other containers to connect to
      - 5433:5432

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U amelia"]
      interval: 5s
      timeout: 5s
      retries: 5

    volumes:
      - pgdata:/var/lib/postgres/data

  amelia-bot:
    container_name: app
    env_file:
      - .env
    build: .
    volumes:
      - .:/app
      - /app/.venv
      - /app/logs
    depends_on:
      postgres_db:
        condition: service_healthy

    extra_hosts:
      - host.docker.internal:host-gateway

volumes:
  pgdata:
    external: true

