version: "3.3"
services:
  postgres_db:
    env_file:
      - .env
    image: postgres:15.4-alpine
    ports: # Set up ports exposed for other containers to connect to
      - 5433:5432
    volumes:
      - pgdata:/var/lib/postgres/data

  amelia-bot:
    container_name: app
    env_file:
      - .env
    network_mode: host
    build: .
    volumes:
      - .:/app
    command: python3.10 -m amelia
    depends_on:
      - postgres_db


volumes:
  pgdata:
    external: true
