CREATE TABLE Guilds
(
    id SERIAL NOT NULL PRIMARY KEY,
    created TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    joined TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    guild_id BIGINT NOT NULL UNIQUE,
    guild_name TEXT NOT NULL,
    member_count INT NOT NULL

);
CREATE OR REPLACE FUNCTION set_updated()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER set_timestamp
        BEFORE UPDATE ON Guilds
        FOR EACH ROW
            EXECUTE PROCEDURE set_updated();

CREATE TRIGGER notify_guilds_event
    AFTER INSERT OR UPDATE OR DELETE ON Guilds
        FOR EACH ROW EXECUTE PROCEDURE notify_event();